name: KRO-Worker Deployment

on:
    push:
        branches:
            - main
    release:
        types: [published]

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
              with:
                ref: main
                fetch-depth: 0

            - name: Copy .env.app
              run: |
                echo "${{ secrets.ENV_PROD }}" >> .env.app
            
            - name: Update Website
              run: |
                git submodule update --recursive --init

            - name: Stop all docker
              run: docker compose down

            - name: Start all docker
              run: |
                export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
                export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
                export POSTGRES_DATABASE=${{ secrets.POSTGRES_DATABASE }}
                docker compose up -d