name: KommtRumathraOnline.de Deploy

on:
    release:
      types: [published]

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Pull Docker images
              run: |
                  docker image pull blackdayz/kommtrumathraonline-worker:latest

            - name: Stop and remove old containers
              run: |
                  docker container stop kommtrumathraonline-worker
                  docker container rm kommtrumathraonline-worker

            - name: Start Worker
              run: |
                  docker run -d --name kommtrumathraonline-worker --env-file ./.prod/.env blackdayz/kommtrumathraonline-worker:latest